# Generated by Django 3.2.18 on 2023-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_event_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Theater', 'Theater'), ('Conference', 'Conference'), ('Concert', 'Concert'), ('Entertainment', 'Entertainment'), ('Live Music', 'Live Music')], max_length=20),
        ),
    ]
