# Generated by Django 3.2.18 on 2023-03-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
