# Generated by Django 3.2.18 on 2023-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_roomservices_servicestype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.CharField(choices=[('Кино', 'Кино'), ('Театр', 'Театр'), ('Конференция', 'Конференция'), ('Концерт', 'Концерт'), ('Развлечения', 'Развлечения'), ('Живая музыка', 'Живая музыка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.CharField(choices=[('Королевская', 'Королевская'), ('Люкс', 'Люкс'), ('Стандарт', 'Стандарт'), ('Эконом', 'Эконом')], max_length=20),
        ),
    ]
