# Generated by Django 3.2.18 on 2023-03-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_event_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='statusEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='statusStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
